let fmt: string = String::format("Hello, {}!", "World");
writeln(fmt);

object CustomConsole {
  fn construct(self) -> void {
    self::prefix = 'LOG';
  }
  
  fn log(self, message: string) -> void {
    let format: string = String::format("[{}]: {}", self::prefix, message);
    writeln(format);
  }
}

let console: CustomConsole = CustomConsole();
console::prefix = 'ERROR';
console::log("hello, world!");